# Generated by Django 4.2 on 2023-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_firebase_ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(default=None, max_length=255),
        ),
    ]
