# Generated by Django 4.2 on 2023-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_firebase_ap', '0002_repository_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
