# Generated by Django 4.2 on 2023-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_firebase_ap', '0003_alter_repository_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamex', models.CharField(max_length=100)),
                ('repositories', models.ManyToManyField(to='github_firebase_ap.repository')),
            ],
        ),
    ]
