# Generated by Django 4.2 on 2023-04-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_firebase_ap', '0005_rename_user_gituser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitUser',
        ),
    ]
