# Generated by Django 4.2 on 2023-04-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_firebase_ap', '0006_delete_gituser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='name',
            new_name='ownername',
        ),
        migrations.AddField(
            model_name='repository',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
