# Generated by Django 4.2 on 2023-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_firebase_ap', '0007_rename_name_repository_ownername_repository_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
